### ISSUE TITLE
Autocomplete in use statement

### ISSUE THREAD

**Issue by ghost** [addiks/gedit-window-management#2]
Hello,
after i have finished the indexing, when i write a use statement it does find the class in autocomplete but it doesn't bring the namespace with the class. So i have to find the namespace through the search index.

**Comment by addiks** [comment]
Can you please provide an example of what you are trying to do? You should never have to write the use-statements yourself, because the plugin add's them automatically when you autocomplete the class-name in the code:

![2017-09-11 gedit-auto-add-use-statement](https://user-images.githubusercontent.com/3450330/30267807-ffeb8b70-96e3-11e7-8150-6eaea89bda32.gif)

Sorry for the late answer, i have missed this issue altogether. I am currently being swarmed with mails from github because i am following a few big projects.

**Comment by addiks** [comment]
I also just realized that you have created this issue in the wrong project. I think you meants to create this issue in this project: https://github.com/addiks/gedit-phpide and not in the window-management plugin-project.

I think it's fine that we handle this issue here for now, but for future issues please create them in the correct project.

**Comment by ghost** [comment]
I was thinking that as i type the suggestion will come automatically, but i have to type Ctrl+Space for the PHP autocompletion to come. Is this how it supposed to work? or maybe there is a conflict with the word autocompletion plugin? Btw your plugin is really useful.

**Comment by addiks** [comment]
This is as it is supposed to work. In other IDE's, the autocomplete popping up got frequently in my way so i made it here that you have to summon it when you actually need it. 
Glad to hear that this plugin is useful to you, Thanks.

This issue seems to be a feature-request because it is currently not intended to provide auto-complete when the users writes the use-statements manually. As i see it there should (nearly) never be a need to write them manually when the computer can just automate that for you. 
I am currently not seeing any urgency in this other than new users stumbling when trying to write the use-statements manually so i will probably not implement this (myself) for quite some time. Others however are welcomed to add this to the plugin. 

If you're ok with this, i will close this issue and create a new one in the correct repository (in a few hours when i am back home).

**Comment by ghost** [comment]
Yes no problem, its better like this you can close it i have another request/issue but i will write it in the right project :)

**Comment by addiks** [comment]
This issue is now replaced with https://github.com/addiks/gedit-phpide/issues/5
